/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "int.h"

uint32_t* EXTI_PR = (uint32_t*) ( EXTI_BASEADDR + 0x14U ) ;

int main(void)
{
	GPIO();
	INT();
	for(;;);
}


void EXTI9_5_IRQHandler(void)
{
    if (*EXTI_PR & (1 << 6))
    {
    	*EXTI_PR |= (1 << 6);
        LED_ON();
    }

    if (*EXTI_PR & (1 << 7))
    {
    	*EXTI_PR |= (1 << 7);
        toggle_LED();
    }

    if (*EXTI_PR & (1 << 8))
    {
    	*EXTI_PR |= (1 << 8);
        LED_OFF();
    }

}
